FROM centos:7
MAINTAINER Alexander Gridnev <gridnev.alexandr@gmail.com>

RUN yum -y update && yum -y upgrade
RUN yum -y install ucspi-tcp python-devel python-setuptools netcat nmap-ncat
RUN easy_install pip

COPY pipelining/requirements.txt /requirements.txt
RUN pip install -r requirements.txt && mkdir /pipeline && touch /pipeline/__init__.py

WORKDIR /pipeline
ENV PYTHONPATH=/pipeline

COPY pipelining /pipeline/pipelining
COPY discovering /pipeline/discovering
